Repository ynput/ayon-jira, pull requests merged in 2024-10, with the labels that each got.

#7 Fix typo in settings
  server/settings/publish_plugins.py
Labels: bug

#9 Chore: Add ruff linting
  .github/workflows/pr_linting.yml
  client/ayon_jira/plugins/publish/collect_jira_credentials.py
  client/ayon_jira/plugins/publish/integrate_jira_comment.py
  create_package.py
  ruff.toml
  server/__init__.py
  server/custom_fields.py
  server/settings/main.py
  server/templates.py
Labels: enhancement

#10 Chore: Updated create package script
  create_package.py
Labels: type: enhancement
